name: B

on:
  workflow_call:

jobs:
  B:
    name: B
    runs-on: ubuntu-latest
    env:
      my_var: 96
    steps:
      - name: B
        run: |
          echo "B"
          echo ${{ env.my_var }}
      - name: Setup environment
        run: |
          echo "{/opt/verilator/bin}" >> $GITHUB_PATH
          RV_ROOT=`pwd`
          echo "RV_ROOT=$RV_ROOT" >> $GITHUB_ENV
          PYTHONUNBUFFERED=1
          echo "PYTHONUNBUFFERED=$PYTHONUNBUFFERED" >> $GITHUB_ENV
          TEST_PATH=$RV_ROOT/verification/test_debug
          echo "TEST_PATH=$TEST_PATH" >> $GITHUB_ENV
      - name: Setup environment
        run: |
          echo "PATH="$PATH
          echo "PYTHONUNBUFFERED="$PYTHONUNBUFFERED
          echo "TEST_PATH="$TEST_PATH
          echo "RV_ROOT="$RV_ROOT
      - name: Print
        run: |
          echo "PR_NUMBER: ${{ github.event.number }}"
          if [ "${{ github.event.number }}" != "" ]; then
            echo "PR number is set"
          else
            echo "PR number is not set"
          fi
