name: B

on:
  workflow_call:

jobs:
  B:
    name: B
    runs-on: ubuntu-latest
    env:
      my_var: 96
    steps:
      - name: B
        run: |
          echo "B"
          echo ${{ env.my_var }}