name: VeeR-EL2 CI

on:
  push:
  pull_request:

jobs:

  A:
    name: A
    runs-on: ubuntu-latest
    steps:
      - name: Install prerequisities
        run: |
          echo "A"

  B:
    name: B
    needs: A
    uses: ./.github/workflows/B.yml
