name: VeeR-EL2 CI

on:
  push:
  pull_request:

jobs:

  A:
    name: A
    runs-on: ubuntu-latest
    steps:
      - name: Install prerequisities
        run: |
          echo "A"

  B:
    name: B
    uses: ./.github/workflows/B.yml

  C:
    name: C
    needs: [A,B]
    uses: ./.github/workflows/B.yml

  D:
    name: D
    uses: ./.github/workflows/C.yml