name: VeeR-EL2 CI

on:
  push:
  pull_request:

jobs:

  Test-Verification:
    name: Test-Verification
    runs-on: ubuntu-latest
    steps:
      - name: Install prerequisities
        run: |
          echo "A"

  Test-Regression:
    name: Test-Regression
    uses: ./.github/workflows/B.yml

  Coverage-Generator:
    name: Coverage-Generator
    needs: [Test-Verification,Test-Regression]
    uses: ./.github/workflows/B.yml

  Publish-Coverage-to-GH-Pages:
    name: Publish-Coverage-to-GH-Pages
    needs: Coverage-Generator
    uses: ./.github/workflows/C.yml

  Publish-PyTestHtml-to-GH-Pages:
    name: Publish-PyTestHtml-to-GH-Pages
    needs: Test-Verification
    uses: ./.github/workflows/C.yml

