name: Cache deposit get
#
on:
  workflow_run:
    workflows: [Cache deposit]
    types:
      - completed

jobs:
    deposit:
      name: deposit
      runs-on: ubuntu-latest
      steps:
        - name: Setup cache
          uses: actions/cache/restore@v3
          id: cache
          with:
            path: |
              ${{ github.workspace }}/.hidden_dir/dir1
              ${{ github.workspace }}/dir2
            key: ${{ env.cache_name }}

        - name: tree
          id: treee
          run: |
            ls -al *
            tree -d
