name: Cache deposit get

on:
  workflow_run:
    workflows: [Cache deposit]
    types:
      - completed

jobs:
    deposit:
      name: deposit
      runs-on: ubuntu-latest
      steps:

        - name: Setup repository
          uses: actions/checkout@v3
          with:
            submodules: recursive

        - name: Install prerequisities2
          run: |
            sudo apt -qqy update && sudo apt -qqy --no-install-recommends install \
            ccache g++

        - name: Setup cache
          uses: actions/cache/restore@v3
          with:
            path: |
              ${{ github.workspace }}/.hidden_dir/dir1
              ${{ github.workspace }}/dir2
              /home/runner/.cache/ccache
            key: cache_2023_05_31

        - name: tree
          id: treee
          run: |
            ls -al *
            tree -d
            cd .hidden_dir
            pwd

        - name: build cpp
          run: |
            ccache -z
            ccache --show-stats
            ccache g++ main.cpp
            ccache --show-stats
            ./a.out